- tap_stripe/__init__.py
- tap_stripe/schemas/payout_transactions.json
- Add `payout_transactions`
- Fix bug where stream/sub_stream wouldn't sync if their bookmarks weren't the same
> Add payout_transactions

- tap_stripe/__init__.py
- tap_stripe/schemas/disputes.json
> Add disputes stream

- tap_stripe/__init__.py
- tap_stripe/schemas/products.json
> Add products stream

- CHANGELOG.md
- setup.py
> Bump to v1.4.0 and update changelog

- CHANGELOG.md
- setup.py
Bumping version for tap-stripe
- none
- none
> patch bump on tap-stripe

- CHANGELOG.md
- setup.py
> Bump to v1.4.4

- .circleci/config.yml
Was added to tap-tester in PR https://github.com/stitchdata/tap-tester/pull/194
- 
- This PR should be merged shortly after the related PR in tap-tester
> Remove pip install of stripe from circle ci

- tests/test_bookmarks.py
Fix logging bug introduced in previous commit.
- 
- None, test change
> fix logging bug in test

- tests/test_bookmarks.py
Fix logging typo in bookmarks test
- 
- 
> fix typo in log

- .circleci/config.yml
Set chron to run daily at 1 pm utc.
- 
- 
> change cron

- tests/test_bookmarks.py
Stabilize bookmarks test by altering assertion. 
- None
- None, test change.
> stabilize bookmarks test

- tap_stripe/schemas/charges.json
- tap_stripe/schemas/customers.json
- tap_stripe/schemas/invoice_items.json
- tap_stripe/schemas/invoice_line_items.json
- tap_stripe/schemas/invoices.json
- tap_stripe/schemas/payouts.json
- tap_stripe/schemas/shared/plan.json
- tap_stripe/schemas/subscription_items.json
- tap_stripe/schemas/subscriptions.json
- 
- low, just schema additions
> add various schema

- CHANGELOG.md
- setup.py
> bump 1.4.5

- CHANGELOG.md
- setup.py
- tap_stripe/schemas/invoices.json
(write a short description or paste a link to JIRA)
- 
- 
> removed schemas that caused transform errors and bump 1.4.6

- CHANGELOG.md
- setup.py
> Revert 1.4.7

- tests/test_all_fields.py
Rework the list of ignored streams to be a dict of fields
- 
- None, this is just a test
> rework all_fields_test to ignore fields rather than streams

- .circleci/config.yml
- tests/test_all_fields.py
Move build time to avoid collisions, use tap_tester_sandbox env.
- 
- 
> use tt_sandbox, move build time

- .circleci/config.yml
- tests/base.py
- tests/test_all_fields.py
Get stripe tests passing, add missing field to known list.
- 
- 
> add 'quote' to known missing field list

- tests/test_all_fields.py
Workaround a missing field in the subscriptions stream.
- 
- 
> adjust all fields test

- .circleci/config.yml
Move schedule back for build_daily.
- 
- 
> move tests back to noon

- .circleci/config.yml
3x the no ouput timeout in circleci for this job
- 
- 
> bump circle no output timeout 3x

- tests/test_all_fields.py
Add another field to the known missing set. Field: `tax_code`  Stream: `products`
- 
- 
> add tax_code to known_missing for products

- .circleci/config.yml
- setup.py
Setup changes.
Make a test group to only install nose and pylint. 
Don't pin ipdb in dev.
- 
- 
> make a test group in setup.py

- tests/test_all_fields.py
Try to stabilize the regression run.
Pulled out the bug and test workarounds to be defined outside of the test class to clean up the assertions.
Removed the workaround that added `'unique_line_item_id'` and `'invoice_item'` to the `invoice_line_items` stream.
- 
- 
> remove a bad workaround

- CHANGELOG.md
- setup.py
> bump 1.5.0

- .circleci/config.yml
https://jira.talendforge.org/browse/TDL-16944
Move build time to avoid conflicts with contractors and internal teams.
6:00am UTC -> 1:00 UTC (8:00pm EST, 6:30am IST)
Move slack notifications to new channel.
- 
- 
> upgrade config

- tap_stripe/schemas/invoices.json
- tap_stripe/schemas/shared/discount.json
- tests/test_all_fields.py
- tests/utils.py
- Added the fields in `KNOWN_MISSING_FIELDS` for invoices stream to the schema
- Removed the fields from `KNOWN_MISSING_FIELDS`.
- 
- 
> Tdl 5894 update invoices stream

- CHANGELOG.md
- setup.py
- Bump version to v2.0.0
- Revert this branch
> Tap-stripe bump version 2.0.0

- tests/test_bookmarks.py
- tests/test_event_updates.py
- tests/test_start_date.py
- tests/utils.py
The tap-tester tests are periodically failing due a race condition in the way that the test client updates payment_intent objects. This will hopefully fix that.
- 
- 
> stabilize tests for payment_intent stream

- CHANGELOG.md
- setup.py
minor bump version 1.5.3
- 
- 
> minor bump version 1.5.3

- CHANGELOG.md
- setup.py
minor bump version 2.0.1
- 
- 
> minor bump version 2.0.1

- CHANGELOG.md
- setup.py
Upgrade latest singer-python version
- 
- 
> Tdl 20714 upgrade singer python version

- setup.py
> Bump version 2.0.2

- CHANGELOG.md
- setup.py
Reverts singer-io/tap-stripe#163
> Revert "Bump version 2.0.2"

- tests/test_all_fields.py
Add fields not being returned by API, TDL-12478
- 
- 
> Add fields not being returned by API, TDL-12478

- tap_stripe/schemas/payment_intents.json
Updates the payment_intents stream to accommodate lists returned for the payment_method_options.card.available_plans field.
- Ran with cloned connection
- Low. Recently implemented field being corrected to prevent transformation errors
> TDL-22056 Change available_plans from object to array

- CHANGELOG.md
- setup.py
Version bump and changelog for [PR 172](https://github.com/singer-io/tap-stripe/pull/172)
- N/A
- Must be released with PR 172
> TDL-22056 Version Bump and Changelog

- tests/test_all_fields.py
- tests/test_automatic_fields.py
- tests/utils.py
Also for now, decreased the payout frequency to monthly on the 1st (from daily).
https://jira.talendforge.org/browse/TDL-21963
- 
- 
> fix expired source, add stripe balance check, spike on payment_method transition

- CHANGELOG.md
- setup.py
Changes in CHANGELOG.md and setup.py
-  
- 
> bump version changes

- tests/test_all_fields.py
> Update all fields test, invoices stream missing 'subscription_details'

- tests/test_all_fields.py
> fix all fields test

- tests/base.py
- tests/test_bookmarks.py
- tests/test_event_updates.py
Skip event update test until TDL-24065 is done
- 
- 
> Skip event update test until TDL-24065 is done

- tests/test_all_fields.py
Add margins to invoice_line_items known missing fields
- 
- 
> Add margins to invoice_line_items known missing fields

- tests/test_all_fields.py
Update all fields test again, invoices and subscriptions
- 
- 
> Update all fields test again

- tests/test_all_fields.py
(write a short description or paste a link to JIRA)
- 
- 
> Update all fields again to add new field being returned in plans stream

- setup.py
- spikes/prior-art/setup.py
- tests/test_all_fields.py
This PR bumps the minor and/or patch versions of various dependencies to fix various CVEs
> Bump versions
